
package codeturing;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class maquina extends javax.swing.JFrame {
    mensaje1 mensa1 = new mensaje1();
    desencriptar Desencriptar=new desencriptar();
    boolean Mj1=false,Mj2=false,Mj3=false;
    /**
     * Creates new form maquina
     */
    public maquina() {
        initComponents();
    }
public Image getIconImage() {
   Image retValue = Toolkit.getDefaultToolkit().
         getImage(ClassLoader.getSystemResource("src/codeturing/imagen/lo_opti.ico"));


   return retValue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mensage = new javax.swing.JTextField();
        limpi = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        encriptado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resul = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Mje1 = new javax.swing.JButton();
        Mje2 = new javax.swing.JButton();
        Mje3 = new javax.swing.JButton();
        Mje7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mensage1 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        resul1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Mje11 = new javax.swing.JButton();
        Mje4 = new javax.swing.JButton();
        Mje5 = new javax.swing.JButton();
        Mje6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        limpi2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setForeground(java.awt.Color.black);
        setIconImages(getIconImages());
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(620, 540));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(660, 558));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POWER SOLVERENCRIP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensaje ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));
        jPanel1.add(mensage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 430, -1));

        limpi.setBackground(new java.awt.Color(153, 153, 153));
        limpi.setForeground(new java.awt.Color(204, 0, 0));
        limpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeturing/imagen/w1_opt (1).png"))); // NOI18N
        limpi.setToolTipText("Limpiar Todo");
        limpi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        limpi.setContentAreaFilled(false);
        limpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpi.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        limpi.setSelected(true);
        limpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiActionPerformed(evt);
            }
        });
        jPanel1.add(limpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 40, 30));

        jToggleButton1.setBackground(new java.awt.Color(153, 153, 153));
        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jToggleButton1.setText("X");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 39, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("V1.0");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 81, -1));

        encriptado.setEditable(false);
        encriptado.setBackground(new java.awt.Color(0, 0, 0));
        encriptado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        encriptado.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(encriptado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 470, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mensaje encriptado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        resul.setEditable(false);
        resul.setBackground(new java.awt.Color(0, 0, 0));
        resul.setColumns(20);
        resul.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        resul.setForeground(new java.awt.Color(0, 153, 0));
        resul.setRows(5);
        resul.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N
        resul.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(resul);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 470, 235));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeturing/imagen/pr_opt.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 360, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mje1.setBackground(new java.awt.Color(51, 51, 51));
        Mje1.setForeground(new java.awt.Color(255, 255, 255));
        Mje1.setText("Mensaje 1");
        Mje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje1ActionPerformed(evt);
            }
        });
        jPanel4.add(Mje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Mje2.setBackground(new java.awt.Color(51, 51, 51));
        Mje2.setForeground(new java.awt.Color(255, 255, 255));
        Mje2.setText("Mensaje 2");
        Mje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje2ActionPerformed(evt);
            }
        });
        jPanel4.add(Mje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        Mje3.setBackground(new java.awt.Color(51, 51, 51));
        Mje3.setForeground(new java.awt.Color(255, 255, 255));
        Mje3.setText("Mensaje 3");
        Mje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje3ActionPerformed(evt);
            }
        });
        jPanel4.add(Mje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        Mje7.setBackground(new java.awt.Color(51, 51, 51));
        Mje7.setForeground(new java.awt.Color(255, 255, 255));
        Mje7.setText("Historia");
        Mje7.setToolTipText("Historial de todo");
        Mje7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje7ActionPerformed(evt);
            }
        });
        jPanel4.add(Mje7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 190, 100, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 410));

        jTabbedPane1.addTab("Encriptar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("POWER SOLVERENCRIP");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mensaje ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        jPanel2.add(mensage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 450, -1));

        jToggleButton2.setBackground(new java.awt.Color(153, 153, 153));
        jToggleButton2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jToggleButton2.setText("X");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 39, -1));

        resul1.setEditable(false);
        resul1.setBackground(new java.awt.Color(0, 0, 51));
        resul1.setColumns(20);
        resul1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        resul1.setForeground(new java.awt.Color(0, 153, 0));
        resul1.setRows(5);
        resul1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        resul1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(resul1);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 130, 470, 350));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("Desencriptar");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mje11.setBackground(new java.awt.Color(51, 51, 51));
        Mje11.setForeground(new java.awt.Color(255, 255, 255));
        Mje11.setText("Historia");
        Mje11.setToolTipText("Historial de todo");
        Mje11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje11ActionPerformed(evt);
            }
        });
        jPanel6.add(Mje11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 190, 100, -1));

        Mje4.setBackground(new java.awt.Color(51, 51, 51));
        Mje4.setForeground(new java.awt.Color(255, 255, 255));
        Mje4.setText("Mensaje 1");
        Mje4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje4ActionPerformed(evt);
            }
        });
        jPanel6.add(Mje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Mje5.setBackground(new java.awt.Color(51, 51, 51));
        Mje5.setForeground(new java.awt.Color(255, 255, 255));
        Mje5.setText("Mensaje 2");
        Mje5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje5ActionPerformed(evt);
            }
        });
        jPanel6.add(Mje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        Mje6.setBackground(new java.awt.Color(51, 51, 51));
        Mje6.setForeground(new java.awt.Color(255, 255, 255));
        Mje6.setText("Mensaje 3");
        Mje6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje6ActionPerformed(evt);
            }
        });
        jPanel6.add(Mje6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeturing/imagen/ana_opt.png"))); // NOI18N
        jLabel7.setText("jLabel3");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 310, 150, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 410));

        limpi2.setBackground(new java.awt.Color(153, 153, 153));
        limpi2.setForeground(new java.awt.Color(204, 0, 0));
        limpi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeturing/imagen/w1_opt (1).png"))); // NOI18N
        limpi2.setToolTipText("Limpiar Todo");
        limpi2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        limpi2.setContentAreaFilled(false);
        limpi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpi2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        limpi2.setSelected(true);
        limpi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpi2ActionPerformed(evt);
            }
        });
        jPanel2.add(limpi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 40, 30));

        jTabbedPane1.addTab("Desencriptrar", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje1ActionPerformed
         String mensaje=this.mensage.getText();
        
         if (mensaje.equals("")) {
          JOptionPane.showMessageDialog(null,"Alerta no a escrito el mensaje1");
        }else{
         try {
           mensaje= mensaje.replaceAll("\\s","");
            mensa1.Encritar(mensaje);
            resul.setText(String.valueOf(">"+mensaje+"\n"+mensa1.lista1 + "\n\n######\n"+mensa1.lista2));
            encriptado.setText(String.valueOf(mensa1.lista2));
            mensage.setText(String.valueOf(""));
             if (mensa1.lista1.equals("")) {
              JOptionPane.showMessageDialog(null,"Error: revise bien el mensaje"); 
              resul.setText(String.valueOf("\n Error: revise bien el mensaje"));
             }else{Mj1=true;}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        } 
         }
        
    }//GEN-LAST:event_Mje1ActionPerformed

    private void limpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiActionPerformed
       mensa1.lista1="";
       mensa1.lista2="";
       mensa1.lista4="";
       mensa1.lista5="";
       mensa1.lista6="";
       mensa1.lista7="";
        mensage.setText(String.valueOf(""));
        resul.setText(String.valueOf(""));
            encriptado.setText(String.valueOf(""));
    }//GEN-LAST:event_limpiActionPerformed

    private void Mje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje2ActionPerformed
       String mensaje2=this.mensage.getText();
        if (mensaje2.equals("")&&Mj1==false) {
             JOptionPane.showMessageDialog(null,"Alerta no a escrito el mensaje1 o esta vacio el mensaje dos");
        } else {
         mensaje2= mensaje2.replaceAll("\\s","");
            mensa1.Encritar2(mensaje2);
             resul.setText(String.valueOf(mensa1.lista5));
      resul.setText(String.valueOf("\n-------mensaje 2-----\n"+mensa1.lista4+"\n ----resul--\n"+mensa1.lista5));
        mensage.setText(String.valueOf(""));
        encriptado.setText(String.valueOf(mensa1.lista5));
        if (mensa1.lista4.equals("")) {
              JOptionPane.showMessageDialog(null,"Error: revise bien el mensaje");   
             }else{Mj2=true;}
        }
      
         
    }//GEN-LAST:event_Mje2ActionPerformed

    private void Mje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje3ActionPerformed
        String mensaje3=this.mensage.getText();
           if (mensaje3.equals("")&&Mj2==false&&Mj3==false) {
            JOptionPane.showMessageDialog(null,"Alerta no a escrito el mensaje1 o esta vacio el mensaje dos o tres");
        } else {
               mensaje3= mensaje3.replaceAll("\\s","");
            mensa1.Encritar3(mensaje3);
             resul.setText(String.valueOf(mensa1.lista7));
      resul.setText(String.valueOf("\n-------mensaje 3-----\n"+mensa1.lista6+"\n ----resul--\n"+mensa1.lista7));
        mensage.setText(String.valueOf(""));
        encriptado.setText(String.valueOf(mensa1.lista7));
               if (mensa1.lista1.equals("")) {
              JOptionPane.showMessageDialog(null,"Error: revise bien el mensaje");   
             }else{Mj1=true;}
        }
       
    }//GEN-LAST:event_Mje3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
         mensage.setText(String.valueOf(""));
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void Mje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje4ActionPerformed
        String mensaje=this.mensage1.getText();
           mensaje= mensaje.replaceAll("\\s","");
            Desencriptar.Desencriptar1(mensaje);
            resul1.setText(String.valueOf(Desencriptar.lista1));
    }//GEN-LAST:event_Mje4ActionPerformed

    private void Mje5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mje5ActionPerformed

    private void Mje6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mje6ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void Mje7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mje7ActionPerformed

    private void Mje11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mje11ActionPerformed

    private void limpi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mje1;
    private javax.swing.JButton Mje11;
    private javax.swing.JButton Mje2;
    private javax.swing.JButton Mje3;
    private javax.swing.JButton Mje4;
    private javax.swing.JButton Mje5;
    private javax.swing.JButton Mje6;
    private javax.swing.JButton Mje7;
    private javax.swing.JTextField encriptado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton limpi;
    private javax.swing.JButton limpi2;
    private javax.swing.JTextField mensage;
    private javax.swing.JTextField mensage1;
    private javax.swing.JTextArea resul;
    private javax.swing.JTextArea resul1;
    // End of variables declaration//GEN-END:variables
}
