
package codeturing;

import javax.swing.JOptionPane;


public class maquina extends javax.swing.JFrame {
    mensaje1 mensa1 = new mensaje1();
 
    /**
     * Creates new form maquina
     */
    public maquina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mensage = new javax.swing.JTextField();
        Mje1 = new javax.swing.JButton();
        Mje2 = new javax.swing.JButton();
        Mje3 = new javax.swing.JButton();
        limpi = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        encriptado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resul = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Super Defenitma");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensaje ");

        Mje1.setBackground(new java.awt.Color(153, 153, 153));
        Mje1.setForeground(new java.awt.Color(51, 51, 51));
        Mje1.setText("Mensaje 1");
        Mje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje1ActionPerformed(evt);
            }
        });

        Mje2.setBackground(new java.awt.Color(153, 153, 153));
        Mje2.setText("Mensaje 2");
        Mje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje2ActionPerformed(evt);
            }
        });

        Mje3.setBackground(new java.awt.Color(153, 153, 153));
        Mje3.setText("Mensaje 3");
        Mje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mje3ActionPerformed(evt);
            }
        });

        limpi.setBackground(new java.awt.Color(153, 153, 153));
        limpi.setForeground(new java.awt.Color(204, 0, 0));
        limpi.setText("Limpiar");
        limpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(153, 153, 153));
        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jToggleButton1.setText("X");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        encriptado.setEditable(false);
        encriptado.setBackground(new java.awt.Color(0, 0, 0));
        encriptado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        encriptado.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mensaje encriptado");

        resul.setEditable(false);
        resul.setBackground(new java.awt.Color(0, 0, 0));
        resul.setColumns(20);
        resul.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        resul.setForeground(new java.awt.Color(0, 153, 0));
        resul.setRows(5);
        resul.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        resul.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(resul);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(mensage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(encriptado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(Mje1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Mje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(Mje3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(160, 160, 160)
                                        .addComponent(limpi))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel1)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mensage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mje1)
                    .addComponent(Mje2)
                    .addComponent(Mje3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(limpi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(encriptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje1ActionPerformed
        try {
            String mensaje=this.mensage.getText();
           mensaje= mensaje.replaceAll("\\s","");
            mensa1.Encritar(mensaje);
            resul.setText(String.valueOf(">"+mensaje+"\n"+mensa1.lista1 + "\n\n######\n"+mensa1.lista2));
            encriptado.setText(String.valueOf(mensa1.lista2));
            mensage.setText(String.valueOf(""));
        } catch (StringIndexOutOfBoundsException n) {
            JOptionPane.showMessageDialog(null,"Error"+n.getMessage());
        }
    }//GEN-LAST:event_Mje1ActionPerformed

    private void limpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiActionPerformed
       mensa1.lista1="";
       mensa1.lista2="";
       mensa1.lista4="";
       mensa1.lista5="";
       mensa1.lista6="";
       mensa1.lista7="";
        mensage.setText(String.valueOf(""));
        resul.setText(String.valueOf(""));
            encriptado.setText(String.valueOf(""));
    }//GEN-LAST:event_limpiActionPerformed

    private void Mje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje2ActionPerformed
         //mensa1.lista1+="\n-------mensaje 2-----\n";
      // mensa1.lista2="";
      String mensaje2=this.mensage.getText();
           mensaje2= mensaje2.replaceAll("\\s","");
            mensa1.Encritar2(mensaje2);
             resul.setText(String.valueOf(mensa1.lista5));
      resul.setText(String.valueOf("\n-------mensaje 2-----\n"+mensa1.lista4+"\n ----resul--\n"+mensa1.lista5));
        mensage.setText(String.valueOf(""));
        encriptado.setText(String.valueOf(mensa1.lista5));
    }//GEN-LAST:event_Mje2ActionPerformed

    private void Mje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mje3ActionPerformed
        String mensaje3=this.mensage.getText();
           mensaje3= mensaje3.replaceAll("\\s","");
            mensa1.Encritar3(mensaje3);
             resul.setText(String.valueOf(mensa1.lista7));
      resul.setText(String.valueOf("\n-------mensaje 3-----\n"+mensa1.lista6+"\n ----resul--\n"+mensa1.lista7));
        mensage.setText(String.valueOf(""));
        encriptado.setText(String.valueOf(mensa1.lista7));
    }//GEN-LAST:event_Mje3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
         mensage.setText(String.valueOf(""));
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mje1;
    private javax.swing.JButton Mje2;
    private javax.swing.JButton Mje3;
    private javax.swing.JTextField encriptado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton limpi;
    private javax.swing.JTextField mensage;
    private javax.swing.JTextArea resul;
    // End of variables declaration//GEN-END:variables
}
